// Generated by gencpp from file proximity_grid/ProximityGridMsg.msg
// DO NOT EDIT!


#ifndef PROXIMITY_GRID_MESSAGE_PROXIMITYGRIDMSG_H
#define PROXIMITY_GRID_MESSAGE_PROXIMITYGRIDMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace proximity_grid
{
template <class ContainerAllocator>
struct ProximityGridMsg_
{
  typedef ProximityGridMsg_<ContainerAllocator> Type;

  ProximityGridMsg_()
    : header()
    , angle_min(0.0)
    , angle_max(0.0)
    , angle_increment(0.0)
    , range_min(0.0)
    , range_max(0.0)
    , ranges()  {
    }
  ProximityGridMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angle_min(0.0)
    , angle_max(0.0)
    , angle_increment(0.0)
    , range_min(0.0)
    , range_max(0.0)
    , ranges(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _angle_min_type;
  _angle_min_type angle_min;

   typedef float _angle_max_type;
  _angle_max_type angle_max;

   typedef float _angle_increment_type;
  _angle_increment_type angle_increment;

   typedef float _range_min_type;
  _range_min_type range_min;

   typedef float _range_max_type;
  _range_max_type range_max;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ranges_type;
  _ranges_type ranges;





  typedef boost::shared_ptr< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ProximityGridMsg_

typedef ::proximity_grid::ProximityGridMsg_<std::allocator<void> > ProximityGridMsg;

typedef boost::shared_ptr< ::proximity_grid::ProximityGridMsg > ProximityGridMsgPtr;
typedef boost::shared_ptr< ::proximity_grid::ProximityGridMsg const> ProximityGridMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proximity_grid::ProximityGridMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proximity_grid::ProximityGridMsg_<ContainerAllocator1> & lhs, const ::proximity_grid::ProximityGridMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angle_min == rhs.angle_min &&
    lhs.angle_max == rhs.angle_max &&
    lhs.angle_increment == rhs.angle_increment &&
    lhs.range_min == rhs.range_min &&
    lhs.range_max == rhs.range_max &&
    lhs.ranges == rhs.ranges;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proximity_grid::ProximityGridMsg_<ContainerAllocator1> & lhs, const ::proximity_grid::ProximityGridMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proximity_grid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a158f75c4b2b1c90453967e931ea138c";
  }

  static const char* value(const ::proximity_grid::ProximityGridMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa158f75c4b2b1c90ULL;
  static const uint64_t static_value2 = 0x453967e931ea138cULL;
};

template<class ContainerAllocator>
struct DataType< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proximity_grid/ProximityGridMsg";
  }

  static const char* value(const ::proximity_grid::ProximityGridMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header 	header\n"
"\n"
"float32   angle_min\n"
"float32   angle_max\n"
"float32   angle_increment\n"
"\n"
"float32   range_min\n"
"float32   range_max\n"
"\n"
"float32[] ranges\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::proximity_grid::ProximityGridMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angle_min);
      stream.next(m.angle_max);
      stream.next(m.angle_increment);
      stream.next(m.range_min);
      stream.next(m.range_max);
      stream.next(m.ranges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProximityGridMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proximity_grid::ProximityGridMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proximity_grid::ProximityGridMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angle_min: ";
    Printer<float>::stream(s, indent + "  ", v.angle_min);
    s << indent << "angle_max: ";
    Printer<float>::stream(s, indent + "  ", v.angle_max);
    s << indent << "angle_increment: ";
    Printer<float>::stream(s, indent + "  ", v.angle_increment);
    s << indent << "range_min: ";
    Printer<float>::stream(s, indent + "  ", v.range_min);
    s << indent << "range_max: ";
    Printer<float>::stream(s, indent + "  ", v.range_max);
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ranges[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROXIMITY_GRID_MESSAGE_PROXIMITYGRIDMSG_H
